DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
--    id bigint PRIMARY KEY AUTO_INCREMENT,
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP,
    checkedAt TIMESTAMP,
    responseCode bigint,
    CONSTRAINT pk_url PRIMARY KEY (id)
);

DROP TABLE IF EXISTS urlChecks;

CREATE TABLE urlChecks (
--    id bigint PRIMARY KEY AUTO_INCREMENT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    urlId bigint,
    statusCode bigint,
    title VARCHAR(255),
    h1 VARCHAR(255),
    description text,
    createdAt TIMESTAMP,
    CONSTRAINT pk_url_checks PRIMARY KEY (id)
);

CREATE INDEX ix_url_check_url_id ON url_checks (url_id);
ALTER TABLE url_checks ADD CONSTRAINT fk_url_checks_url_id FOREIGN KEY (url_id) REFERENCES urls (id) ON DELETE RESTRICT ON UPDATE RESTRICT;